### ISSUE TITLE
SHIPYRD_HOST should be sat in deploy.yml and .env

### ISSUE THREAD

**Issue by AliOsm** [Shipyrd/shipyrd#29]
When I'm trying to run `kamal deploy`, triggering hooks are failing with `SHIPYRD_HOST` environment variable is not available, but it exists in `deploy.yml`.

When I added it to `.env` file it worked. I think this should be added to the documentation.

**Comment by AliOsm** [comment]
I think this makes sense, but if this is the case, I think it is better to move `SHIPYRD_HOST` to the secrets part, and use `.env` to set it.

**Comment by nickhammond** [comment]
@AliOsm What version of Kamal are you using? 1.4 or 1.5+?

**Comment by AliOsm** [comment]
I'm using `1.5.2`.

**Comment by nickhammond** [comment]
Docs updated, thank you @AliOsm!
