### ISSUE TITLE
Should I set the username manually for GitHub CLI?

### ISSUE THREAD

**Issue by AliOsm** [Shipyrd/shipyrd#30]
Sorry for the long list of issues, but I'm trying to report anything not clear I face when setting up Shipyrd.

To get the performer, you are using `gh config get -h github.com username`, and if it is not available you are using `ENV["KAMAL_PERFORMER"]`.

When I run `gh config get -h github.com username` manually on terminal, I get `could not find key "username"`, but when I set it manually using `gh config set username AliOsm`, it works.

Should I set the username manually?

I think something like `gh api user | jq -r '.login'` will work better, no?

**Comment by nickhammond** [comment]
@AliOsm Ideally you run `gh config set username AliOsm` and it sets it. `gh api user | jq -r '.login'` requires an API call and we don't want to rely on that during a deploy. I'll spend some time fixing up this username lookup, appreciate the feedback and you testing things out!

The gem outlines everything that gets recorded as well if you're curious on how that part works:
https://github.com/Shipyrd/shipyrd-gem?tab=readme-ov-file#recording-a-deploy

**Comment by AliOsm** [comment]
This integrates will with a devcontainer, you can set the username as a post devcontainer creation script to not forget about it.

**Comment by nickhammond** [comment]
@AliOsm Would you mind sharing that script?

**Comment by AliOsm** [comment]
So, I'm using devcontainer as my development environment. I created a `.devcontainer/setup.sh` file and added `gh config set username AliOsm` at the end of it. Also, I added `"ghcr.io/devcontainers/features/github-cli:1": {}` as the devcontainer feature. In this way once I build the devcontainer, I have everything ready.
